backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;
glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

opacity-rule = [
  "75:class_g = 'org.wezfurlong.wezterm'"
];

# https://picom.app/picom.1.html?utm_source=chatgpt.com
# Informationa about blurring
blur:
{
  method = "dual_kawase";
  strength = 8;
};

blur-background = true;

blur-background-rule = [
  "class_g = 'org.wezfurlong.wezterm'"
];
