format = """$time$directory$git_branch$git_status$git_metrics$cmd_duration
$character"""

add_newline = false

[directory]
format = "[$path]($style) "
style = "bold #7DF9AA"
truncation_length = 3

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold #FCF392"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold #FF6E6E"

[git_metrics]
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
added_style = "bold #7DF9AA"
deleted_style = "bold #FF6E6E"
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "bold #8B8B8B"
min_time = 2_000

[character]
success_symbol = '[➜](bold #7DF9AA)'
error_symbol = '[✗](bold #FF6E6E)'

[time]
disabled = false
time_format = "%R"
format = "[$time]($style) "
style = "bold #8DFBD2"
