local ls = require('luasnip')
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
    s('Mont', {
        t('\\Mont{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('bit', {
        t('\\bit'),
        i(0),
    }),
    s('poly', {
        t('\\poly'),
        i(0),
    }),
    s('GeneralP', {
        t('\\GeneralP{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('GeneralB', {
        t('\\GeneralB{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Indicator', {
        t('\\Indicator{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('IndicatorFunc', {
        t('\\IndicatorFunc'),
        i(0),
    }),
    s('BigO', {
        t('\\BigO{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('BigOTilde', {
        t('\\BigOTilde{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('SmallO', {
        t('\\SmallO{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('BigOmega', {
        t('\\BigOmega{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('SmallOmega', {
        t('\\SmallOmega{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('TightTheta', {
        t('\\TightTheta{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Def', {
        t('\\Def'),
        i(0),
    }),
    s('Complement', {
        t('\\Complement{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Inner', {
        t('\\Inner{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('TwoNormSquared', {
        t('\\TwoNormSquared{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('OneNorm', {
        t('\\OneNorm{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Dist', {
        t('\\Dist'),
        i(0),
    }),
    s('DistSet', {
        t('\\DistSet{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Naturals', {
        t('\\Naturals'),
        i(0),
    }),
    s('Integers', {
        t('\\Integers'),
        i(0),
    }),
    s('Reals', {
        t('\\Reals'),
        i(0),
    }),
    s('FieldPolynomials', {
        t('\\FieldPolynomials'),
        i(0),
    }),
    s('RealPolynomials', {
        t('\\RealPolynomials'),
        i(0),
    }),
    s('Field', {
        t('\\Field'),
        i(0),
    }),
    s('RegularGraphFam', {
        t('\\RegularGraphFam{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('SizeRamsey', {
        t('\\SizeRamsey{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Edges', {
        t('\\Edges{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Vertices', {
        t('\\Vertices{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('NumEdges', {
        t('\\NumEdges{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('NumVertices', {
        t('\\NumVertices{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('CompleteGraph', {
        t('\\CompleteGraph{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Ramsey', {
        t('\\Ramsey{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Subdivided', {
        t('\\Subdivided{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Neighbourhood', {
        t('\\Neighbourhood{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Laplace', {
        t('\\Laplace'),
        i(0),
    }),
    s('NP', {
        t('\\NP'),
        i(0),
    }),
    s('Alphabet', {
        t('\\Alphabet'),
        i(0),
    }),
    s('instance', {
        t('\\instance'),
        i(0),
    }),
    s('proof', {
        t('\\proof'),
        i(0),
    }),
    s('Proof', {
        t('\\Proof'),
        i(0),
    }),
    s('Verifier', {
        t('\\Verifier'),
        i(0),
    }),
    s('Prover', {
        t('\\Prover'),
        i(0),
    }),
    s('st', {
        t('\\st'),
        i(0),
    }),
    s('Nbrhood', {
        t('\\Nbrhood{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Identity', {
        t('\\Identity'),
        i(0),
    }),
    s('Exp', {
        t('\\Exp{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('OWF', {
        t('\\OWF'),
        i(0),
    }),
    s('Mean', {
        t('\\Mean{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Meann', {
        t('\\Meann{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Var', {
        t('\\Var{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Algorithm', {
        t('\\Algorithm{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Prob', {
        t('\\Prob{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Probb', {
        t('\\Probb{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('PProb', {
        t('\\PProb{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('money', {
        t('\\money'),
        i(0),
    }),
    s('samples', {
        t('\\samples'),
        i(0),
    }),
    s('samplesNonUniform', {
        t('\\samplesNonUniform{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('iidSamples', {
        t('\\iidSamples'),
        i(0),
    }),
    s('Faces', {
        t('\\Faces{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('ConvHull', {
        t('\\ConvHull{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Dim', {
        t('\\Dim{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Size', {
        t('\\Size{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Simplex', {
        t('\\Simplex'),
        i(0),
    }),
    s('SimplicialComplex', {
        t('\\SimplicialComplex'),
        i(0),
    }),
    s('Polyhedron', {
        t('\\Polyhedron{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Uniform', {
        t('\\Uniform{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('stationary', {
        t('\\stationary'),
        i(0),
    }),
    s('mixingTime', {
        t('\\mixingTime'),
        i(0),
    }),
    s('neighbourhood', {
        t('\\neighbourhood{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('energy', {
        t('\\energy{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Energy', {
        t('\\Energy{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Volume', {
        t('\\Volume{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Variance', {
        t('\\Variance{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Path', {
        t('\\Path{'),
        i(1),
        t('}{'),
        i(2),
        t('}{'),
        i(3),
        t('}'),
        i(0),
    }),
    s('PathDist', {
        t('\\PathDist{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Domain', {
        t('\\Domain'),
        i(0),
    }),
    s('Samp', {
        t('\\Samp{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Cond', {
        t('\\Cond{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('IntCond', {
        t('\\IntCond{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('PairCond', {
        t('\\PairCond{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('DomainSize', {
        t('\\DomainSize'),
        i(0),
    }),
    s('Fail', {
        t('\\Fail'),
        i(0),
    }),
    s('TV', {
        t('\\TV{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Tester', {
        t('\\Tester'),
        i(0),
    }),
    s('Graph', {
        t('\\Graph'),
        i(0),
    }),
    s('CutEdges', {
        t('\\CutEdges{'),
        i(1),
        t('}{'),
        i(2),
        t('}{'),
        i(3),
        t('}'),
        i(0),
    }),
    s('IncidentEdges', {
        t('\\IncidentEdges{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('CutEdgesSet', {
        t('\\CutEdgesSet{'),
        i(1),
        t('}{'),
        i(2),
        t('}{'),
        i(3),
        t('}'),
        i(0),
    }),
    s('red', {
        t('\\red{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('green', {
        t('\\green{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('RedNodes', {
        t('\\RedNodes{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('GreenNodes', {
        t('\\GreenNodes{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('GreenB', {
        t('\\GreenB'),
        i(0),
    }),
    s('RedA', {
        t('\\RedA'),
        i(0),
    }),
    s('FuncDomain', {
        t('\\FuncDomain'),
        i(0),
    }),
    s('Claim', {
        t('\\Claim{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('PHP', {
        t('\\PHP{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('FPHP', {
        t('\\FPHP{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('OntoPHP', {
        t('\\OntoPHP{'),
        i(1),
        t('}{'),
        i(2),
        t('}'),
        i(0),
    }),
    s('Refute', {
        t('\\Refute{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Pseudowidth', {
        t('\\Pseudowidth{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('HeavyPigeons', {
        t('\\HeavyPigeons{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Closure', {
        t('\\Closure{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('ClosureParam', {
        t('\\ClosureParam{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('Span', {
        t('\\Span{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('domain', {
        t('\\domain{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('False', {
        t('\\False'),
        i(0),
    }),
    s('CollisonProb', {
        t('\\CollisonProb{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('LTwo', {
        t('\\LTwo{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('LOne', {
        t('\\LOne{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('boundary', {
        t('\\boundary{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('PrimeOrder', {
        t('\\PrimeOrder'),
        i(0),
    }),
    s('GField', {
        t('\\GField{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('MLE', {
        t('\\MLE{'),
        i(1),
        t('}'),
        i(0),
    }),
    s('eq', {
        t('\\eq'),
        i(0),
    }),
}
